version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/api/src/clean-node-api/dist
      - ./package.json:/api/src/clean-node-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo